apiVersion: apps/v1
kind: Deployment
metadata:
  name: facts-deploy
  labels:
    app: facts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facts
  template:
    metadata:
      labels:
        app: facts
    spec:
      containers:
        - name: facts
          image: facts:0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client-service
spec:
  clusterIP: 10.104.149.195
  clusterIPs:
    - 10.104.149.195
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - nodePort: 31542
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: client
  type: NodePort